 glove_dir : '../../animesh/glove/'
 data_file : 'data.txt'
 num_classes: 2
 embedding_size : 50
 vocab_length : 400000
 learning_rate : 0.001
 dropout : 0.5
 num_filters: 50
 vocab_file : 'voc.txt'
 embedding_file: 'emb.txt'
 not_exist_index : 400000
 max_document_length : 1475